# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e2c5d27a31b77624125eaa5b5e9b84e59788c3ea111f58821b23e1384ae7b861c3e7b3ca3edfec421e3b74d88da657a8f0653bbcac67552b7964901e8d8fd69

test:
  secret_key_base: 56ac69a47c52f3124cde77346481f7776197f190312a28a60d9e1cd518c79ed7c4ae787fdeba34ac099c882cf7c97172cd7d0b7c5839458f75ca5f7eef06f0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
