# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 530e67eb0aec4caf5a450fa05cd124a95393ab2f0b450bc3a14fc8fc777b74ab4cff7417416764e4c74f072c27a5fd2fc69b5fbc3d3c7fc2791605f1b20136a4

test:
  secret_key_base: 716874fb9983f4361966996bc554ebfc82a90e1195c42f2c0169a9746b6de1327bd0fd24f596ad7fd3b603bf69fd824e1c7053343d272022d805c06aac7be348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
